module main

import net.mbedtls
import time

// 7-day trial. The build time comes from build_stamp.v (regenerated by
// build.bat on every build, see tools/stamp) and "now" comes from the Date
// header of HTTPS servers whose certificates must chain to the roots pinned
// in trial_pins.v, so neither the PC clock nor a faked time server extends
// the trial. While the
// app runs, time advances with the monotonic clock (immune to clock changes)
// and is re-synced from the network every hour.

struct TimeSource {
	host string
	// PEM roots this host's certificate chain must end in.
	roots string
}

// Plain NTP is unauthenticated, so only pinned HTTPS sources are used.
const time_sources = [
	TimeSource{host: 'www.google.com', roots: pin_google_roots},
	TimeSource{host: 'www.cloudflare.com', roots: pin_google_roots},
	TimeSource{host: 'www.microsoft.com', roots: pin_digicert_g2},
	TimeSource{host: 'www.apple.com', roots: pin_digicert_g2},
]
const trial_resync_seconds = 3600.0
// Network time earlier than the build (minus clock skew) means a fake time source.
const trial_skew_seconds = i64(86400)

struct Trial {
mut:
	build   i64
	expires i64
	// Last trusted network time and the monotonic clock reading at that moment.
	anchor      i64
	anchor_mono u64
	last_sync   u64
}

fn rotl64(v u64, n int) u64 {
	return (v << u64(n)) | (v >> u64(64 - n))
}

// Inverse of an odd number mod 2^64 (Newton: each step doubles the correct bits).
fn inv64(m u64) u64 {
	mut r := m
	for _ in 0 .. 5 {
		r *= 2 - m * r
	}
	return r
}

// Must match fold in tools/stamp/stamp.v.
fn stamp_fold(t u64, e u64, m u64, x u64) u64 {
	mut h := x ^ 0x9e3779b97f4a7c15
	h = (h ^ t) * 0xbf58476d1ce4e5b9
	h = rotl64(h, 31) ^ (e * m)
	h = (h ^ (h >> 29)) * 0x94d049bb133111eb
	return h ^ (h >> 32)
}

// Decodes the build and expiry times; fails if the constants were tampered with.
fn decode_stamp() !(i64, i64) {
	mi := inv64(k_m)
	t := ((k_a ^ k_x) * mi) - k_o
	e := ((k_b ^ rotl64(k_x, 23)) * mi) - k_o2
	if stamp_fold(t, e, k_m, k_x) != k_c || e - t != u64(7 * 24 * 60 * 60) {
		return error('bad stamp')
	}
	return i64(t), i64(e)
}

// Date header of `HEAD /` over TLS that trusts only `src.roots`; the
// handshake fails unless the chain ends in a pinned root and the
// certificate matches the host name.
fn https_time(src TimeSource) !i64 {
	mut conn := mbedtls.new_ssl_conn(
		verify:                 src.roots
		in_memory_verification: true
		validate:               true
	)!
	defer {
		conn.shutdown() or {}
	}
	conn.dial(src.host, 443)!
	conn.duration = 5 * time.second
	conn.write_string('HEAD / HTTP/1.1
Host: ${src.host}
User-Agent: CubeWatch
Connection: close

')!
	mut head := []u8{}
	mut buf := []u8{len: 4096}
	for head.len < 65536 && !head.bytestr().contains('

') {
		n := conn.read(mut buf) or { break }
		head << buf[..n]
	}
	for line in head.bytestr().split('
') {
		if line.to_lower().starts_with('date:') {
			return time.parse_rfc2822(line[5..].trim_space())!.unix()
		}
	}
	return error('no Date header from ${src.host}')
}

// First valid time from the pinned sources.
fn network_time() !i64 {
	for src in time_sources {
		if t := https_time(src) {
			return t
		}
	}
	return error('no network time')
}

fn mono_seconds() u64 {
	return time.sys_mono_now() / 1_000_000_000
}

fn (mut tr Trial) sync() ! {
	t := network_time()!
	tr.anchor = t
	tr.anchor_mono = mono_seconds()
	tr.last_sync = tr.anchor_mono
}

fn (tr &Trial) now() i64 {
	return tr.anchor + i64(mono_seconds() - tr.anchor_mono)
}

fn (tr &Trial) expired() bool {
	n := tr.now()
	return n >= tr.expires || n < tr.build - trial_skew_seconds
}

fn (tr &Trial) days_left() int {
	left := tr.expires - tr.now()
	return if left <= 0 { 0 } else { int((left + 86399) / 86400) }
}

// Call periodically; re-syncs with the network every hour (a failed sync
// keeps counting on the monotonic clock). Returns false once expired.
fn (mut tr Trial) still_valid() bool {
	if f64(mono_seconds() - tr.last_sync) >= trial_resync_seconds {
		tr.sync() or { tr.last_sync = mono_seconds() }
	}
	return !tr.expired()
}

fn trial_message(text string) {
	C.MessageBoxW(unsafe { nil }, text.to_wide(), '${app_title} - trial'.to_wide(), mb_iconerror)
}

fn trial_expired_text(expires i64) string {
	return 'The trial period ended on ${time.unix(expires).local().format()}.'
}

// Verifies the trial at startup; shows a message and returns an error when
// the app must not run.
fn start_trial() !Trial {
	build, expires := decode_stamp() or {
		trial_message('This copy is damaged. Please download it again.')
		return err
	}
	mut tr := Trial{
		build:   build
		expires: expires
	}
	tr.sync() or {
		trial_message('Cannot verify the trial period: no internet time server could be reached.\n\nConnect to the internet and start ${app_title} again.')
		return err
	}
	if tr.expired() {
		trial_message(trial_expired_text(expires))
		return error('expired')
	}
	return tr
}
