module main

import crypto.rand
import os
import time

// Writes build_stamp.v with the build time encoded under fresh random keys.
// build.bat runs it before every compile, so each build gets a new trial
// window and different constants.
//
// Encoding (all u64, wrapping):
//   k_a = ((t + o) * m) ^ x            t = build unix time
//   k_b = ((e + o2) * m) ^ rotl(x, 23) e = expiry unix time
//   k_c = fold(t, e, m, x)             integrity check, see trial.v
// m is odd so it has an inverse mod 2^64; the app derives it at runtime.

const trial_days = 7

fn rnd() u64 {
	return rand.int_u64(max_u64) or { panic(err) }
}

fn rotl(v u64, n int) u64 {
	return (v << u64(n)) | (v >> u64(64 - n))
}

// Must match stamp_fold in trial.v.
fn fold(t u64, e u64, m u64, x u64) u64 {
	mut h := x ^ 0x9e3779b97f4a7c15
	h = (h ^ t) * 0xbf58476d1ce4e5b9
	h = rotl(h, 31) ^ (e * m)
	h = (h ^ (h >> 29)) * 0x94d049bb133111eb
	return h ^ (h >> 32)
}

fn main() {
	out := if os.args.len > 1 { os.args[1] } else { 'build_stamp.v' }
	t := u64(time.utc().unix())
	e := t + u64(trial_days) * 86400
	m := rnd() | 1
	x := rnd()
	o := rnd()
	o2 := rnd()
	k_a := ((t + o) * m) ^ x
	k_b := ((e + o2) * m) ^ rotl(x, 23)
	k_c := fold(t, e, m, x)
	src := '// Generated by tools/stamp at build time. Do not edit or commit.
module main

const k_m = u64(0x${m:016x})
const k_x = u64(0x${x:016x})
const k_o = u64(0x${o:016x})
const k_o2 = u64(0x${o2:016x})
const k_a = u64(0x${k_a:016x})
const k_b = u64(0x${k_b:016x})
const k_c = u64(0x${k_c:016x})
'
	os.write_file(out, src) or {
		eprintln('stamp: ${err}')
		exit(1)
	}
	exp := time.unix(i64(e))
	println('Trial stamp: built ${time.unix(i64(t)).format_ss()} UTC, expires ${exp.format_ss()} UTC')
}
